config/routes.rb
Rails.application.routes.draw do
  resources :courses
  root 'home#index'
  # get 'static_pages/landing_page'
  # get 'static_pages/privacy_policy'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/course.rb
class Course < ApplicationRecord
    has_rich_text :description
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/courses_controller.rb
class CoursesController < ApplicationController
  before_action :set_course, only: %i[ show edit update destroy ]

  # GET /courses or /courses.json
  def index
    @courses = Course.all
  end

  # GET /courses/1 or /courses/1.json
  def show
  end

  # GET /courses/new
  def new
    @course = Course.new
  end

  # GET /courses/1/edit
  def edit
  end

  # POST /courses or /courses.json
  def create
    @course = Course.new(course_params)

    respond_to do |format|
      if @course.save
        format.html { redirect_to course_url(@course), notice: "Course was successfully created." }
        format.json { render :show, status: :created, location: @course }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @course.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /courses/1 or /courses/1.json
  def update
    respond_to do |format|
      if @course.update(course_params)
        format.html { redirect_to course_url(@course), notice: "Course was successfully updated." }
        format.json { render :show, status: :ok, location: @course }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @course.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /courses/1 or /courses/1.json
  def destroy
    @course.destroy

    respond_to do |format|
      format.html { redirect_to courses_url, notice: "Course was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_course
      @course = Course.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def course_params
      params.require(:course).permit(:title, :description)
    end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def landing_page
  end

  def privacy_policy
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/courses_helper.rb
module CoursesHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/active_storage/blobs/_blob.html.erb
<figure class="attachment attachment--<%= blob.representable? ? "preview" : "file" %> attachment--<%= blob.filename.extension %>">
  <% if blob.representable? %>
    <%= image_tag blob.representation(resize_to_limit: local_assigns[:in_gallery] ? [ 800, 600 ] : [ 1024, 768 ]) %>
  <% end %>

  <figcaption class="attachment__caption">
    <% if caption = blob.try(:caption) %>
      <%= caption %>
    <% else %>
      <span class="attachment__name"><%= blob.filename %></span>
      <span class="attachment__size"><%= number_to_human_size blob.byte_size %></span>
    <% end %>
  </figcaption>
</figure>

app/views/courses/_form.html.haml
-# frozen_string_literal: true
= stylesheet_pack_tag 'application', media: 'all', 'data-turbolinks-track': 'reload'
= simple_form_for(@course) do |f|
  = f.error_notification
  = f.error_notification message: f.object.errors[:base].to_sentence if f.object.errors[:base].present?

  .form-inputs
    = f.input :title
    = f.label :description
    = f.rich_text_area :description

  .form-actions
    = f.button :submit

app/views/courses/edit.html.haml
%h1 Editing course

= render 'form'

= link_to 'Show', @course
\|
= link_to 'Back', courses_path

app/views/courses/index.html.haml
%h1 Listing courses

%table
  %thead
    %tr
      %th Title
      %th Description
      %th
      %th
      %th

  %tbody
    - @courses.each do |course|
      %tr
        %td= course.title
        %td= course.description
        %td= link_to 'Show', course
        %td= link_to 'Edit', edit_course_path(course)
        %td= link_to 'Destroy', course, method: :delete, data: { confirm: 'Are you sure?' }

%br

= link_to 'New Course', new_course_path

app/views/courses/new.html.haml
%h1 New course

= render 'form'

= link_to 'Back', courses_path

app/views/courses/show.html.haml
%p#notice= notice

%p
  %b Title:
  = @course.title
%p
  %b Description:
  = @course.description

= link_to 'Edit', edit_course_path(@course)
\|
= link_to 'Back', courses_path

app/views/home/index.html.haml
%nav.navbar.navbar-expand-lg.navbar-light.bg-light
  .container-fluid
    %a.navbar-brand{:href => "#"}
      %i.fa-solid.fa-house>
      Navbar
    %button.navbar-toggler{"aria-controls" => "navbarSupportedContent", "aria-expanded" => "false", "aria-label" => "Toggle navigation", "data-bs-target" => "#navbarSupportedContent", "data-bs-toggle" => "collapse", :type => "button"}
      %span.navbar-toggler-icon
    #navbarSupportedContent.collapse.navbar-collapse
      %ul.navbar-nav.me-auto.mb-2.mb-lg-0
        %li.nav-item
          %a.nav-link.active{"aria-current" => "page", :href => "#"} Home
        %li.nav-item
          %a.nav-link{:href => "#"} Link
        %li.nav-item.dropdown
          %a#navbarDropdown.nav-link.dropdown-toggle{"aria-expanded" => "false", "data-bs-toggle" => "dropdown", :href => "#", :role => "button"}
            Dropdown
          %ul.dropdown-menu{"aria-labelledby" => "navbarDropdown"}
            %li
              %a.dropdown-item{:href => "#"} Action
            %li
              %a.dropdown-item{:href => "#"} Another action
            %li
              %hr.dropdown-divider/
            %li
              %a.dropdown-item{:href => "#"} Something else here
        %li.nav-item
          %a.nav-link.disabled Disabled
      %form.d-flex
        %input.form-control.me-2{"aria-label" => "Search", :placeholder => "Search", :type => "search"}/
        %button.btn.btn-outline-success{:type => "submit"} Search
.container-fluid
  %h1 Hello word
  %p Find me in app/views/home/index.html.erb


  .fa.fa-flag 
  .fab.fa-amazon 
= link_to root_path do
  .fa.fa-home
= link_to courses_path,class: 'btn btn-success' do
  .fa.fa-book
  Courses

app/views/layouts/application.html.haml
!!!
%html
  %head
    %meta{:content => "text/html; charset=UTF-8", "http-equiv" => "Content-Type"}/
    %title RubyStudy
    = csrf_meta_tags
    = csp_meta_tag
    = stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload'
    = javascript_pack_tag 'application', 'data-turbolinks-track': 'reload'
    = stylesheet_pack_tag 'application', media: 'all', 'data-turbolinks-track': 'reload'
  %body
    = yield

app/views/static_pages/landing_page.html.haml
%nav.navbar.navbar-expand-lg.navbar-light.bg-light
  .container-fluid
    %a.navbar-brand{:href => "#"}
      %i.fa-solid.fa-house>
      Navbar
    %button.navbar-toggler{"aria-controls" => "navbarSupportedContent", "aria-expanded" => "false", "aria-label" => "Toggle navigation", "data-bs-target" => "#navbarSupportedContent", "data-bs-toggle" => "collapse", :type => "button"}
      %span.navbar-toggler-icon
    #navbarSupportedContent.collapse.navbar-collapse
      %ul.navbar-nav.me-auto.mb-2.mb-lg-0
        %li.nav-item
          %a.nav-link.active{"aria-current" => "page", :href => "#"} Home
        %li.nav-item
          %a.nav-link{:href => "#"} Link
        %li.nav-item.dropdown
          %a#navbarDropdown.nav-link.dropdown-toggle{"aria-expanded" => "false", "data-bs-toggle" => "dropdown", :href => "#", :role => "button"}
            Dropdown
          %ul.dropdown-menu{"aria-labelledby" => "navbarDropdown"}
            %li
              %a.dropdown-item{:href => "#"} Action
            %li
              %a.dropdown-item{:href => "#"} Another action
            %li
              %hr.dropdown-divider/
            %li
              %a.dropdown-item{:href => "#"} Something else here
        %li.nav-item
          %a.nav-link.disabled Disabled
      %form.d-flex
        %input.form-control.me-2{"aria-label" => "Search", :placeholder => "Search", :type => "search"}/
        %button.btn.btn-outline-success{:type => "submit"} Search
.container-fluid
  %h1 Hello word
  = link_to "Private Policy",privacy_policy_path, class: 'btn btn-lg btn-warning'

app/views/static_pages/privacy_policy.html.haml
%h1 StaticPages#privacy_policy
%p Find me in app/views/static_pages/privacy_policy.html.erb
= link_to "Home",root_path